version: '3.7'
services:

  rabbitmq1:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"    
      - "5672:5672"
    networks:
      - iot-labs
    labels:
      NAME: "rabbitmq1"


  mongo:
    image: mongo:4.2.0-bionic
    hostname: "mongo"
    restart: always
    labels:
      NAME: "mongo"
    networks:
      - iot-labs
    ports:
      - 27017:27017

  nifi:
    image: "apache/nifi:1.9.2"
    hostname: "nifi"
    environment:
      NIFI_WEB_HTTP_PORT: "8080"
    ports:
      - "8083:8080"
    networks:
      - iot-labs
    labels:
      NAME: "nifi"
   

  mongo-express:
    image: mongo-express:0.49.0
    hostname: "mongo_express"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    labels:
      NAME: "mongo_express"
    networks:
      - iot-labs

  influxdb:
    image: "influxdb"
    hostname: "influxdb"
    ports:
      - "8086:8086"
    networks:
      - iot-labs
    labels:
      NAME: "influxdb"

  influxdbchrono:
    image: "chronograf"
    hostname: "chronograf"
    ports:
      - "8087:8888"
    networks:
      - iot-labs
    labels:
      NAME: "chronograf"
    command: "--influxdb-url=http://influxdb:8086"


  grafana:
    image: "grafana/grafana"
    hostname: "grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    ports:
      - "8084:3000"
    networks:
      - iot-labs
    labels:
      NAME: "grafana" 


networks:
  iot-labs:
    external: true