version: '3.7'
services:

  nifi:
    image: "apache/nifi:1.9.2"
    hostname: "nifi"
    environment:
      NIFI_WEB_HTTP_PORT: "8080"
    ports:
      - "8083:8080"
    networks:
      - iot-labs
    labels:
      NAME: "nifi"
  
  mongo:
    image: mongo:4.2.0-bionic
    hostname: "mongo"
    restart: always
    labels:
      NAME: "mongo"
    networks:
      - iot-labs
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.49.0
    hostname: "mongo_express"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    labels:
      NAME: "mongo_express"
    networks:
      - iot-labs

networks:
  iot-labs:
    external: true